exclude: '^(docs/conf.py|tests/testdata/.*)'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.5
  hooks:
    - id: ruff          # linter
      types_or: [ python, pyi, jupyter ]
      args: [--fix]
    - id: ruff-format   # formatter
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.358
  hooks:
    - id: pyright
      additional_dependencies: [ "equinox", "jax", "lineax", "optimistix", "pytest" ]
