name: Build docs

on:
  push:
    branches:
      - main

# These permissions are required for it to work
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.pages_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install -r docs/requirements.txt

      - name: Build docs
        run: |
          mkdocs build
          mkdocs build  # twice, see https://github.com/patrick-kidger/pytkdocs_tweaks

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload docs
        uses: actions/upload-pages-artifact@v2
        with:
          path: site  # where `mkdocs build` puts the built site

      - name: Deploy to GitHub Pages
        id: deployment # This is required for environment
        uses: actions/deploy-pages@v3
